### ISSUE TITLE
无法下载下架歌曲

### ISSUE THREAD

**Issue by twilightgod** [EraserKing/CloudMusicGear#12]
- Operating system: Windows 10
- Client type (Desktop / UWP), version: Desktop 2.0.1
- PAC mode / Proxy mode: Set to 127.0.0.1:3413
- Overseas or not, CDN used or not, which CDN: Overseas with Cloud Music VIP
- Song / Album / Playlist name (how I can locate to that song): http://music.163.com/#/m/song?id=254409
- Whether the issue happens on specific songs, or all songs: repro on many songs
- Whether it can be reproduced on web client for the same song

Logs:
[5:42:41 PM]: New URL is http://m1.music.126.net/hmZoNQaqzZALvVp0rE7faA==/0.mp3
[5:42:42 PM]: This song http://m1.music.126.net/hmZoNQaqzZALvVp0rE7faA==/0.mp3 is not available on the server.

通过这个网站可以下载，应该是解析有问题
http://www.loadfield.com/project/163/song.php?id=254409

**Comment by EraserKing** [comment]
I tracked the new client and found the APIs have changed a lot.
What's worse, the returned value of a key API called by the client seems encrypted and I don't know how it works.
So I'm afraid the way the utility is working won't be effective any more. I'm not able to discover a new way now.

Closing.

**Comment by twilightgod** [comment]
Can I revert to an old version? Which one should I use?

**Comment by EraserKing** [comment]
You could try 2.0.1 or 2.0.2 client, which hasn't taken the new encrypted API yet, according to my memory. Mine is 2.0.3 now and I don't have an older installer.

However, I'm afraid perhaps an older version won't even work, as the same API return encrypted value instead of plain text in the past.
Even it may work, I don't want everybody using an older client which may not function at any time.

The neat solution to me is to decrypt the new return value, which I don't think it's possible in the past.
