### ISSUE TITLE
Switching from copyright tracks causes crash.

### ISSUE THREAD

**Issue by legendtang** [EraserKing/CloudMusicGear#9]
- Windows 10 10586
- Desktop 2.0.2 128316
- Proxy mode
- Not oversea or using CDNs
- http://music.163.com/#/album?id=34407429
- All songs
- No
![photo_2016-03-30_18-21-08](https://cloud.githubusercontent.com/assets/1352729/14139201/34693032-f6a4-11e5-9c93-a5d1ce2116a2.jpg)

其实在之前的命令行版本也是相同的问题，使用一段时间后虽然还能看到日志里面有 API 的输出但是客户端就无限加载了，此时还不会崩溃，保持一段时间则会崩溃。

最近听一张版权砖的时候尤为明显，正常曲目和版权曲目混合时估计几小时一次，纯版权曲目则几分钟。由于看不到相关 verbose 的日志所以根据个人体验认为是快速切换两首版权曲目时，上一个版权曲目的逻辑未处理完成而请求另一首版权曲目会造成崩溃。

**Comment by EraserKing** [comment]
Yes, your guess is right. If you skip tracks very frequently it may not response properly after a while, but as this is quite rare on my side, I haven't tried to solve it. I didn't see its crash but this is indeed possible. I'll keep an eye on it.

Thanks for your info.

**Comment by legendtang** [comment]
@EraserKing Once you catch it, you may reproduce if you don't close them immediately but just wait for a while.

**Comment by EraserKing** [comment]
It seems my guess is not accurate. On my side, the rare failure of playback is caused by the lack of some files on m2 server, but not the utility itself.

Anyway, I made some changes, then tried the album you mentioned. I played it for all the afternoon (around 4 hours) and it didn't crash, or not responding either.

I'll continue testing it tomorrow and publish it if I cannot reproduce.

**Comment by legendtang** [comment]
@EraserKing It seems some files in this album on CDNs expired today (Many tracks expired today). So we are talking two different issues. In my case, it fails to work every several switches (within minutes), then go crashing.

I've also tried build from source or override some settings but no locks.

**Comment by EraserKing** [comment]
@legendtang Yes, two issues here :)
1. I also met that but not as severe as your description (crash). I did some changes and hope that works.
2. But some issues were caused by the changes of CDN which I have no solution.

Anyway I'll try and see if there's any improvement on the stability.

**Comment by EraserKing** [comment]
@legendtang I did some changes and for a whole one day it doesn't crash. I'll put the test version here and you could try. I'll deal with another big pull request which may cost me several days and I don't want to keep you waiting for a long time.

[CMG_test.zip](https://github.com/EraserKing/CloudMusicGear/files/199037/CMG_test.zip)

**Comment by legendtang** [comment]
@EraserKing I don't know what you have changed but it seems not working for me. My friend and I have talk about this, and we all believe that it was caused by async unsafe multi request that your dependencies in C# do not handle it so well. But node.js natively supports async http calls so he has implemented another tool (https://github.com/ITJesse/UnblockNeteaseMusic) like this, which you might have probably knew. That works for me.

**Comment by legendtang** [comment]
I think the project is dead again as almost all copyright tracks on CDN have expired. Will reopen if there is new way to bypass the limitation.

**Comment by EraserKing** [comment]
@legendtang I'm sorry as I indeed cannot reproduce your issues (crashing) on my side. I adjusted some parameters but it seems not working to you. If the root cause is really what you described, I'm afraid there is nothing I could do - it's a closed source 3rd party library which I cannot modify at all.

Frankly speaking, FiddlerCore is the best proxy library I can find for C#, and I have no intention to implement one by myself. Besides, as far as I know, the tool you mentioned has some weird behaviors on Windows platform. I don't know the details but I'm wondering if it shares the same issue as mine.

About the expiration of tracks, I don't have chance to try it today (or during the vacation). If it's true, I could announce the project is terminated again :)
